dataSources:
  - type: file
    sources:
#      - /Users/oyejide/Documents/agenthub-docs
#      - /Users/oyejide/Downloads/questions
      - /Users/oyejide/Desktop/eb1_application/llm_docs
    location: null

  - type: confluence
    sources:
      - "123456"  # Confluence page ID
      - "789012"  # Another page ID
    location: "https://company.atlassian.net"

  - type: url
    sources:
      - "https://example.com/resource1"
      - "https://example.com/resource2"
    location: null

  - type: s3
    sources:
      - "bucket1/path/to/file1.pdf"
      - "bucket1/path/to/file2.txt"
    location: "s3://my-bucket"
